title = "Ruderclub Kleinmachnow Stahnsdorf Teltow e.V."
baseURL = "https://wanderrudern.de"

theme = "kstview"

languageCode = "de"
defaultContentLanguage = "de"

# -- build-specifics start --
relativeUrls = true
timeout = "120"
staticDir = ["static", ] # "site_archive"
# -- build-specifics end --

[params]
backdrop_image = "bundle/backdrops/club-gelaende.jpg"
icon_image = "bundle/kst_wikingerschiff_simplistic_light.svg"

font_url = "bundle/noto-sans/NotoSans-Medium.ttf"
list.articles_per_site = 50
list.card_width = "50pt"

# TODO: Use menu items
home.nav_items = [ "/neuigkeiten", "/ausschreibungen", "/berichte", "/intern" ]

author.name = "Paul Seydel"
author.email = "Seydel.fnvd@gmail.com"

footer.socials = [
    { image = "bundle/facebook-icon-light.svg", href ="https://www.facebook.com/wanderrudern" },
]
# key is the translation key
footer.links = { imprint = "/club/impressum", data_protection = "/club/datenschutz" }

meta.publisher = "Ruderclub Kleinmachnow Stahnsdorf Teltow"
meta.copyright = "Stefan Biastock"
meta.page_topic = "Sport"
meta.page_type = "Vereinspage"
meta.revisit_after = "4 weeks"
meta.default_tags = [
    "Wanderrudern","Rudern","wanderrudern","rudern","rowing","Ruderboot","Ruderer","Freizeit",
    "Sport","Fun","Berlin", "Kleinmachnow","Stahnsdorf","Teltow","Wassersport","Jugendliche",
    "Jugend","Fahrten","Reisen","reisen","Wanderfahrten","Abenteuer","adventure","Ruderclub",
    "Ruderverein","row","rower","Babelsberg","Potsdam","Zehlendorf"
]

cookiebanner.more_here = "https://commission.europa.eu/cookies-policy"

[taxonomies]
gewaesser = "gewaesser"
land = "land"

[services.googleAnalytics]
id = ""
[privacy.GoogleAnalytics]
disable = true

[languages.de]
languageName = "Deutsch"
weight = 20

[languages.en]
languageName = "English"
weight = 10

[permalinks.page]
berichte = '/berichte/:year/:month/:slug'
neuigkeiten = '/neuigkeiten/:year/:month/:slug'

[renderer]
unsafe = false
