_merge = "shallow" # deep

title = "Ruderclub Kleinmachnow Stahnsdorf Teltow e.V."
baseURL = "https://wanderrudern.de"

theme = "kstview"

languageCode = "de"
defaultContentLanguage = "de"

staticDir = ["static"] #, "archive"]

[params]
archive_base = "/archive"
backdrop_image = "bundle/backdrops/club-gelaende.jpg"
icon_image = "bundle/kst_wikingerschiff_simplistic_light.svg"

font_url = "bundle/noto-sans/NotoSans-Medium.ttf"
list.articles_per_site = 50
list.card_width = "50pt"

# TODO: Use menu items
home.nav_items."Club" = "/club"
home.nav_items."Neuigkeiten" = "/neuigkeiten"
home.nav_items."Berichte" = "/berichte"
home.nav_items."Ausschreibungen" = "/ausschreibungen"

home.english_basepage = "/introduction"
home.news_count = 10
home.trip_announcement_count = 10

author.name = "Stefan Biastock"
author.email = "info@wanderrudern.de"

footer.socials = [
    { image = "bundle/facebook-icon-light.svg", href ="https://www.facebook.com/wanderrudern" },
]

# key is the translation key
footer.links.imprint = "/club/impressum"
footer.links.data_protection = "/club/datenschutz"

meta.publisher = "Ruderclub Kleinmachnow Stahnsdorf Teltow"
meta.copyright = "Stefan Biastock"
meta.page_topic = "Sport"
meta.page_type = "Vereinsseite"
meta.revisit_after = "4 weeks"
meta.default_tags = [
    "Wanderrudern","Rudern","wanderrudern","rudern","rowing","Ruderboot","Ruderer","Freizeit",
    "Sport","Fun","Berlin", "Kleinmachnow","Stahnsdorf","Teltow","Wassersport","Jugendliche",
    "Jugend","Fahrten","Reisen","reisen","Wanderfahrten","Abenteuer","adventure","Ruderclub",
    "Ruderverein","row","rower","Babelsberg","Potsdam","Zehlendorf"
]

cookiebanner.more_here = "https://commission.europa.eu/cookies-policy"
cookiebanner.data_protection = "/club/datenschutz"

[[params.vorstand]]
position = ["1. Vorstand", "Sport/Wanderruderwart"]
name = "Stefan Biastock"
email = "info@wanderrudern.de"
nummer = "0172-405 92 53"

[[params.vorstand]]
position = ["2. Vorstand", "Verwaltung"]
name = "Martin Beilfuß"
email = "martin@wanderrudern.de"
nummer = "033203-24948"

[[params.vorstand]]
position = "Kassenwart"
name = "Dr. Ulrich Schmidt"
email = "kassenwart@wanderrudern.de"

[[params.vorstand]]
position = "Schriftführer"
name = ""
email = "post@wanderrudern.de"

[[params.vorstand]]
position = "Ruderwart Erwachsene"
name = ["Thomas Schmidt-Lehmann", "Florian Coesfeld", "Peter Strauß"]
email = "rudern@wanderrudern.de"

[[params.vorstand]]
position = "Ruderwart Jugend"
name = ["Carlos Fisch" , "Timo Schlichting"]
email = "jugendwart@wanderrudern.de"

[[params.vorstand]]
position = "Ruderwart Marathon"
name = "Nirina Beilfuß"
email = "marathon@wanderrudern.de"

[[params.vorstand]]
position = "Bootswarte"
name = ["Wolfgang Petri", "Tim Czemper"]
email = "bootswart@wanderrudern.de"
nummer = ["0173-2355261", "0176-79259096"]

[[params.vorstand]]
position = "Hauswart"
name = "Sandro Genrich"
email = "hauswart@wanderrudern.de"

[[params.vorstand]]
position = "PR-Öffentlichkeit"
name = "Simone Pelzer"
email = "pressewart@wanderrudern.de"
nummer = "0173-4609836"

[[params.vorstand]]
position = "PR-Sponsoring"
name = "Kai Wadewitz"
email = "sponsoring@wanderrudern.de"

[[params.vorstand]]
position = "Veranstaltungen"
name = ""
email = ""

[taxonomies]
"gewässer" = "gewässer"
"land" = "länder"
"typ" = "typen"

#[languages.de]
#weight = 20
#languageName = "Deutsch"
#
#[languages.en]
#disabled = true
#weight = 10
#languageName = "English"

