baseURL = "https://wanderrudern.de"
relativeUrls = true
title = "Ruderclub Kleinmachnow Stahnsdorf Teltow e.V."

theme = "kstview"

languageCode = "de"
defaultContentLanguage = "de"
staticDir = ["static", "images", "site_archive"]

[taxonomies]
waters = "waters"

[params]
backdrop_image = "bundle/backdrops/club-gelaende.jpg"
icon_image = "bundle/kst_wikingerschiff_simplistic_light.svg"
font_url = "bundle/noto-sans/NotoSans-Medium.ttf"
articles_per_site = 20

home.nav_items = [ "/berichte", "/neuigkeiten", "/intern" ]
params.footer.facebook = "https://www.facebook.com/wanderrudern"

[params.author]
name = "Paul Seydel"
email = "Seydel.fnvd@gmail.com"

[params.meta]
publisher = "Ruderclub Kleinmachnow Stahnsdorf Teltow"
copyright = "Stefan Biastock"
page_topic = "Sport"
page_type = "Vereinspage"
revisit_after = "4 weeks"
default_tags = [
    "Wanderrudern","Rudern","wanderrudern","rudern","rowing","Ruderboot","Ruderer","Freizeit",
    "Sport","Fun","Berlin", "Kleinmachnow","Stahnsdorf","Teltow","Wassersport","Jugendliche",
    "Jugend","Fahrten","Reisen","reisen","Wanderfahrten","Abenteuer","adventure","Ruderclub",
    "Ruderverein","row","rower","Babelsberg","Potsdam","Zehlendorf"
]


[services.googleAnalytics]
id = ""
[privacy.GoogleAnalytics]
disable = false


[languages.de]
languageName = "Deutsch"
weight = 20

[languages.en]
languageName = "English"
weight = 10

[permalinks.page]
berichte = '/berichte/:year/:month/:slug'
neuigkeiten = '/neuigkeiten/:year/:month/:slug'

[permalinks.section]
berichte = '/berichte'
neuigkeiten = '/neuigkeiten'
intern = "/intern"

[renderer]
unsafe = false
