baseURL = 'http://wanderrudern.de'
languageCode = 'de'
defaultContentLanguage = 'de'
title = 'Vereinswebsite Ruderclub Kleinmachnow Stahnsdorf Teltow e.V.'

[taxonomies]
  tag = "Tags"
  waters = "Gewässer"

[Author]
  name = "Paul Seydel"
  email = "Seydel.fnvd@gmail.com"

staticDir = ["static", "images", "site_archive"]

[languages.de]
languageName = "Deutsch"
weight = 20

[languages.en]
languageName = "English"
weight = 10
