title = "Ruderclub Kleinmachnow Stahnsdorf Teltow e.V."
baseURL = "https://wanderrudern.de"


theme = "kstview"

languageCode = "de"
defaultContentLanguage = "de"
staticDir = ["static", "site_archive"]

relativeUrls = true
timeout = "120"

[taxonomies]
waters = "waters"

[params]
backdrop_image = "bundle/backdrops/club-gelaende.jpg"
icon_image = "bundle/kst_wikingerschiff_simplistic_light.svg"
font_url = "bundle/noto-sans/NotoSans-Medium.ttf"
articles_per_site = 50

home.nav_items = [ "/neuigkeiten", "/ausschreibungen", "/berichte", "/intern" ]
params.footer.facebook = "https://www.facebook.com/wanderrudern"

author.name = "Paul Seydel"
author.email = "Seydel.fnvd@gmail.com"

meta.publisher = "Ruderclub Kleinmachnow Stahnsdorf Teltow"
meta.copyright = "Stefan Biastock"
meta.page_topic = "Sport"
meta.page_type = "Vereinspage"
meta.revisit_after = "4 weeks"
meta.default_tags = [
    "Wanderrudern","Rudern","wanderrudern","rudern","rowing","Ruderboot","Ruderer","Freizeit",
    "Sport","Fun","Berlin", "Kleinmachnow","Stahnsdorf","Teltow","Wassersport","Jugendliche",
    "Jugend","Fahrten","Reisen","reisen","Wanderfahrten","Abenteuer","adventure","Ruderclub",
    "Ruderverein","row","rower","Babelsberg","Potsdam","Zehlendorf"
]


[services.googleAnalytics]
id = ""
[privacy.GoogleAnalytics]
disable = true


[languages.de]
languageName = "Deutsch"
weight = 20

[languages.en]
languageName = "English"
weight = 10

[permalinks.page]
berichte = '/berichte/:year/:month/:slug'
neuigkeiten = '/neuigkeiten/:year/:month/:slug'

[permalinks.section]
berichte = '/berichte'
neuigkeiten = '/neuigkeiten'
intern = "/intern"

[renderer]
unsafe = false
