baseURL: 'https://wanderrudern.de'
title: 'Ruderclub Kleinmachnow Stahnsdorf Teltow e.V.'

taxonomies:
  waters: "waters"

Author:
  name: "Paul Seydel"
  email: "Seydel.fnvd@gmail.com"

params:
  defaultMetaTags: [Wanderrudern,Rudern,wanderrudern,rudern,rowing,Ruderboot,Ruderer,Freizeit,Sport,Fun,Berlin, Kleinmachnow,Stahnsdorf,Teltow, Wassersport,Jugendliche,Jugend,Fahrten,Reisen,reisen,Wanderfahrten,Abenteuer,adventure,Ruderclub,Ruderverein,row,rower,Babelsberg,Potsdam,Zehlendorf]

languageCode:  'de'
defaultContentLanguage:  'de'
languages:
  de:
    languageName: "Deutsch"
    weight: 20
  en:
    languageName: "English"
    weight: 10

staticDir: ["static", "images", "site_archive"]
