languageCode = "de"
defaultContentLanguage = "de"

# -- build-specifics start --
relativeUrls = true
timeout = "120"
# -- build-specifics end --

[services.googleAnalytics]
id = ""
[privacy.GoogleAnalytics]
disable = true

#[permalinks.page]
#berichte = '/berichte/:year/:month/:slug'
#neuigkeiten = '/neuigkeiten/:year/:month/:slug'
#ausschreibungen = '/ausschreibungen/:year/:month/:slug'

[markup.goldmark.renderer]
unsafe = true

#[markup.goldmark.parser]
#wrapStandAloneImageWithinParagraph = false
[markup.goldmark.renderHooks.link]
enableDefault = true

[security]
enableInlineShortcodes = true
